### ISSUE TITLE
VSCode Extension never recognizes that I have Az.Tools.Migration installed

### ISSUE THREAD

**Issue by d-duer** [Azure/azure-powershell-migration#112]
**Component**
[X] VSCode extension

**Description of the issue**
Every time I open up VSCode, I get the "You have to install Az.Tools.Migration firstly!" error. I do have it installed though. Below is a simplified version of the code that the extension uses in extension.ts and powershell.ts:

```
import * as fs from 'fs';
import * as path from 'path';

const PsModulePathes = process.env.PSMODULEPATH.split(";");
const moduleName = "Az.Tools.Migration";
const systemModulePath = PsModulePathes


console.log(systemModulePath.some(
    moduleFolder => fs.existsSync(path.resolve(moduleFolder, moduleName))))
```

When I run that through a typescript debugger within VSCode, it logs 'True'. I noticed that the shell the extension opens up uses -noProfile and executionPolicy: 'Bypass'. Using noprofile locally still returns the same paths in $env:psmodulepath, so I don't think that has anything to do with it. However, when I try to set my execution policy to bypass, I get the following:
```
Set-ExecutionPolicy : Access to the registry key                                                                        
'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell' is denied. To change the execution   
policy for the default (LocalMachine) scope, start Windows PowerShell with the "Run as administrator" option. To        change the 
execution policy for the current user, run "Set-ExecutionPolicy -Scope CurrentUser".                         At line:1 char:1                                                                                                        
+ Set-ExecutionPolicy                                                                                                   + ~~~~~~~~~~~~~~~~~~~                                                                                                       
+ CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], UnauthorizedAccessException                      + FullyQualifiedErrorId : 
System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.SetExecutionPolicyComma     nd
```  

Could the extension be bombing out due to that error and not recognizing the existence of the module because of it?

**Comment by alexandair** [comment]
I'm experiencing the same problem for a couple of months. I've seen other people complaining too.

**Comment by d-duer** [comment]
So I was wrong about the 'Bypass' suggestion; that wasn't it. The output of `process.env.PSMODULEPATH.split(";")` when ran from the extension is `['C:\Program Files\WindowsPowerShell\Modules', 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules']`, but my `$env:PSModulePath `when run from a Powershell window (including the Powershell terminal within VScode) is `C:\Users\dduer\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules`. I don't know anything about TS/JS so I don't know the reason behind the difference, but I'm gonna see if I can figure it out

**Comment by tccack** [comment]
I have the same issue. Installed module without issues but each launch I get the error too that I need to install firstly.

**Comment by stefanstranger** [comment]
I also get this error message.

![image](https://github.com/Azure/azure-powershell-migration/assets/2125385/98695b30-2787-44f6-9ae9-5735e8ceb58a)

While I've the module installed in all possible locations....
![image](https://github.com/Azure/azure-powershell-migration/assets/2125385/1f5d36a1-b279-415e-87cc-974b5a35389b)

Please fix this issue. 

Stefan [MSFT]

**Comment by stefanstranger** [comment]
Resolved by running:

```PowerShell
save-module az.tools.migration -Path C:\Windows\system32\WindowsPowerShell\v1.0\Modules
```

from elevated host.

**Comment by tccack** [comment]
Champion!!!

**Comment by VeryEarly** [comment]
> Even after fixing the module issue, I still can't get the extension to do any syntax highlighting. Think I'm just gonna give up on this and use the migration module by itself.

Hi, 
the bug that extension doesn't work was fixed, please try az.tools.migration 2.0.0+

**Comment by VeryEarly** [comment]
> Resolved by running:
> 
> ```powershell
> save-module az.tools.migration -Path C:\Windows\system32\WindowsPowerShell\v1.0\Modules
> save-module az.tools.migration -Path "C:\program files\powershell\7\Modules"
> save-module az.tools.migration -Path "C:\Program Files\WindowsPowerShell\Modules"
> ```
> 
> from elevated host.

yes the version 2.0.0 is not installed in the expected location. I'll consider scan more possible locations. Thanks for reporting.
