### ISSUE TITLE
Not recognizing few commands

### ISSUE THREAD

**Issue by Narenadv** [Azure/azure-powershell-migration#117]
**Component**
 PowerShell module

**Description of the issue**
New-AzUpgradeModulePlan doesnot recognize few commands like Get-Module AzureRm.Profile,
Invoke-AzureRmDataFactoryV2Pipeline, Start-AzureRmDataFactoryV2Trigger, Clear-AzureRmContext, Azurerm.sql

**Describe how to reproduce the issue**
Use those commands and try to modify it. Confirm me if its not working.

**Environment**
dev

**Comment by isra-fel** [comment]
@VeryEarly hi, did you get the chance to test these cmdlets?

**Comment by VeryEarly** [comment]
-  `Clear-AzureRmContext` is able to be recognized with no problem
- `Invoke-AzureRmDataFactoryV2Pipeline`, `Start-AzureRmDataFactoryV2Trigger` have been fixed #133 , will be available in Az.Tools.Migration 11.0.1
- `AzureRm.Profile`, `AzureRM.sql` are not in current scope of this tool, I'll consider whether we should migrate these module names or other terms need to be included.
