### ISSUE TITLE
Find-AzUpgradeCommandReference -DirectoryPath no longer works as of 2.0.0

### ISSUE THREAD

**Issue by kbrady-msft** [Azure/azure-powershell-migration#121]
**Component**
[x] PowerShell module
[] VSCode extension
[] Other

**Description of the issue**
Find-AzUpgradeCommandReference no longer works for with ` -DirectoryPath` because the call to:

```powershell
        $FilePath = (Resolve-Path $FilePath).Path
```

Is always invoked.

**Describe how to reproduce the issue**
Try to use Find-AzUpgradeCommandReference with -DirectoryPath

**Environment**
Looks like this was introduced with 2.0.0

**Error output**
```
Resolve-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\Az.Tools.Migration\2.0.0\Functions\Public\Find-AzUpgradeCommandReference.ps1:95 char:35
+         $FilePath = (Resolve-Path $FilePath).Path
+                                   ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Resolve-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.ResolvePathCommand
```

**Additional context**
Add any other context or screenshots about the issue here.

**Comment by Nothing-Works** [comment]
it's been a few weeks, any updates? @VeryEarly @dolauli the `FilePath` flag is not working either, so the tool is not useable at all or is there a workaround to make it work?

**Comment by jluckins** [comment]
+1 here - seams totally non functional at the moment using the -path or -file path flags. Was troubleshooting the error on my end for a few minutes then came to the GitHub Repo to report but found its already noted *Of cause it is* :)
