### ISSUE TITLE
please update latest AzureRM version from 6.13.1 to 6.13.2

### ISSUE THREAD

**Issue by jyama4ta** [Azure/azure-powershell-migration#132]
**Component**
[x] PowerShell module
[] VSCode extension
[] Other

**Description of the issue**
Currently, AzureRM latest version is 6.13.2. Please update the hard-coded version from 6.13.1 to 6.13.2.

**Describe how to reproduce the issue**
specify '-FromAzureRmVersion' to 6.13.2 and got an error.

**Environment**
PS C:\Users\WDAGUtilityAccount> Get-InstalledModule -Name AzureRM

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
6.13.2     AzureRM                             PSGallery            Azure Resource Manager Module

PS C:\Users\WDAGUtilityAccount> Get-InstalledModule -Name Az.Tools.Migration

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
11.0.0     Az.Tools.Migration                  PSGallery            Contains functionality to upgrade PowerShell scripts and modules from AzureRM to Az.

**Error output**
New-AzUpgradeModulePlan : Cannot validate argument on parameter 'FromAzureRmVersion'. The argument "6.13.2" does not belong to the set "6.13.1" specified by the ValidateSet attribute.
Supply an argument that is in the set and then try the command again.
At line:1 char:53
+ $Plan = New-AzUpgradeModulePlan -FromAzureRmVersion 6.13.2 -ToAzVersi ...
+                                                     ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzUpgradeModulePlan], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-AzUpgradeModulePlan

**Additional context**
Add any other context or screenshots about the issue here.

**Comment by VeryEarly** [comment]
@isra-fel do you have context whether there are different syntax between 6.13.1 and 6.13.2

**Comment by VeryEarly** [comment]
support both azurerm versions even if there are no obvious differences between 6.13.1 and 6.13.2

**Comment by jyama4ta** [comment]
@VeryEarly , @isra-fel ,
Are there any update about this? With the upcoming retirement of AzureRM module, there is a need for a prompt update to this conversion tool.

**Comment by isra-fel** [comment]
@VeryEarly do you think we can plan it in this sprint or next?

**Comment by jyama4ta** [comment]
Hello @isra-fel , @VeryEarly , 
AzureRM module will retire this month. Currently, many customers are trying to migrate their scripts. I hope this issue will fix soon.
