### ISSUE TITLE
Add splatted parameter handling support

### ISSUE THREAD

**Issue by keithbabinec** [Azure/azure-powershell-migration#57]
**Component**
[x] PowerShell module
[x] VSCode extension
[] Other

**Description of the new feature**
Upgrade plans will emit a warning for splatted parameters, saying that they should be unrolled before upgrading. It would be nice if the module was able to detect and update splatted parameters if they are defined in the same file.

**Describe the solution you'd like**
Upgrade plans should be able to update parameter names in splatted parameter collections.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dcaro** [comment]
@keithbabinec do you have any timeline about this issue?

**Comment by keithbabinec** [comment]
@dcaro -- I haven't looked at it recently, but I will spend some time on it this week.
