### ISSUE TITLE
A typo in the PlanResultReason property

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell-migration#66]
In the announcement blog post there is a screenshot that shows a typo in the PlanResultReason property.
 "it's aliases" should be "its aliases".

![az-tools-migration2a.jpg](https://user-images.githubusercontent.com/3135708/94609933-cbf7c380-029f-11eb-8059-d5b1d34ef2ce.jpg)

**Comment by keithbabinec** [comment]
Updated PR #64 to include that typo fix. Thanks!
