### ISSUE TITLE
Add support for Resourcegroup deployment with custom parameters

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell-migration#72]
**Component**
[X] PowerShell module
[] VSCode extension
[] Other

**Description of the new feature**
Az.Tools.Migration does not support `New-AzResourceGroupDeployment` with custom parameters.

**Describe the solution you'd like**
We could be looking only at the known parameters for this cmdlet since the custom ones cannot be identified before hand and may vary.
We may want to consider a logging a warning in the plan so customers can have a closer look.

**Comment by keithbabinec** [comment]
I think I may have some ideas for how to handle this a little bit better. Will take a look soon.
